### ISSUE TITLE
Logistical Transporter/Pressurized Tube auto-eject not working, multipart bug.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2049]
When i have this setup, something seems to cause the auto-eject function to not work propatly. Was shown in the video attached below, removing the Plank Cover under the Logistical Transporter solves the problem. I'm guessing that there is something odd with the mulipart implementation.

Note that there is a Pressurized Tube under covered in Plank Covers. I've experienced this issue on Mekanism v6 and v7. Also tried the latest build: 1.7.10-7.1.1.144 (Used in the video).

Here is a video showing the bug:
https://www.youtube.com/watch?v=wuC8oJ6t3iw

**Comment by aidancbrady** [comment]
Fixed!

**Comment by halvors** [comment]
@aidancbrady Could you reopen this please? I'm still experiencing exactly the same issue as showed in the video on Mekanism 8.0.1.198 :-1:

**Comment by aidancbrady** [comment]
Strange. I'll look into it

**Comment by halvors** [comment]
Excellent :)

**Comment by aidancbrady** [comment]
Fixed after much code digging.  I was checking for a valid connection on the opposite side I was supposed to be, silly me.

**Comment by halvors** [comment]
Nice :)
