### ISSUE TITLE
TransmitterNetwork lag

### ISSUE THREAD

**Issue by sfPlayer1** [aidancbrady/Mekanism#2139]
Mekanism cause lag spikes, e.g. as seen in http://creepgaming.com/nps/spike4.nps (VisualVM compatible), where it spends 3.3 seconds within a single tick building some network as a followup on ae2 loading a chunk.

The connectivity lookup into unloaded chunks problem I mentioned at https://github.com/CrazyPants/EnderIO/issues/1959 seems to apply to Mekanism as well.

**Comment by halvors** [comment]
I am alsp experiencing this issue.

**Comment by halvors** [comment]
@aidancbrady may you priority this issue? Ir really makes the game unplayable :-(

**Comment by sfPlayer1** [comment]
Another nps, 12s spike, showing it more clearly and originating from Mekanism's own tick:
http://creepgaming.com/nps/spike-12067-50323413.nps

**Comment by aidancbrady** [comment]
Just found what I think to be the source of the issue - each of those chunk load calls originated from a transmitter checking for an adjacent, active redstone connection with "isBlockIndirectlyGettingPowered()."  It looks like that method force loads chunks without checking if they exist, and then that chunk load triggers other transmitters to do the same check, resulting in the halt.

I just developed my own redstone check, after I push the build this should no longer occur.

**Comment by aidancbrady** [comment]
Just pushed the build to master, should be fixed.

**Comment by halvors** [comment]
Hmm. Still getting the lag. It seems to be a little bit better, but it's still there :-(

**Comment by sfPlayer1** [comment]
It's still loading chunks, see http://creepgaming.com/nps/spike-2074-189208754.nps

Afaik the method you are calling reaches 2 blocks far, but you only check 1.

**Comment by halvors** [comment]
@aidancbrady May you reopen this issue?

**Comment by unpairedbracket** [comment]
Hopefully I've just fixed it fully, please test 176 when it's finished compiling.

**Comment by sfPlayer1** [comment]
Actually I think you didn't since it can go like this, where S = start, N = neighbor, Q = blocks also queried:
```
  Q
 QNQ
QNSNQ
 QNQ
  Q
```
A proper check would require to check all neighbors and their neighbors, or better and faster just check World.doChunksNearChunkExist(te.xCoord, te.yCoord, te.zCoord, 2).

**Comment by aidancbrady** [comment]
@sfPlayer1, check out my fix in the previous commit - I'm almost positive it fixes your issue as mentioned, but I'd appreciate a second pair of eyes.

**Comment by sfPlayer1** [comment]
It looks good in terms of not loading extra chunks from what I can tell.

I'm not sure if you want to check weak power from the direct neighbors as well and whether the implementation can cause cases of being unable to turn the rs signal off due to the indirect queries checking the original block as well. The 2nd case of course only applies if the block interacts with redstone in a bidirectional fashion.

**Comment by aidancbrady** [comment]
It doesn't, but for future reference, what would be the best way around that?

-aidancbrady

**Comment by sfPlayer1** [comment]
Add a source direction to the 2nd pass calls, don't check its opposite.

**Comment by halvors** [comment]
@sfPlayer1 Can you confirm if this works now with the latest build? Still experiencing some lag on my server, but it may not be Mekanism related.

**Comment by sfPlayer1** [comment]
I can't test it myself, some sampler profiling info from elsewhere is needed (presumably spike triggered).

**Comment by sfPlayer1** [comment]
I've just noticed a somewhat related problem, this time with PartSidedPipe(?), which is likely not fixed yet. It happened with an older build though, but the redstone fix was very specific.

A nps file showing the problem can be found at http://files.player.to/tmp/spike-2918-1551299993_out.nps

**Comment by unpairedbracket** [comment]
What fun. Any idea what on earth could be causing that? Apart from just a very large network of transmitters across many chunks?

**Comment by aidancbrady** [comment]
I may be missing something, but the nps file indicates an issue relating to AE2.

**Comment by aidancbrady** [comment]
http://puu.sh/gLmAJ/ca9f4cb25e.png

**Comment by unpairedbracket** [comment]
Keep digging. It does look like AE2 has a problem too, but it's not as bad as ours.

**Comment by unpairedbracket** [comment]
I think notifyTileChange has similar issues to the redstone method that was causing issues before.

**Comment by aidancbrady** [comment]
Ah - that's pretty deep. Yeah, that must be the problem.

**Comment by unpairedbracket** [comment]
The call in [this line](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartSidedPipe.java#L579) is loading all adjacent chunks to each chunk we load, worst case. I guess we write a new non-loading implementation if possible.

**Comment by sfPlayer1** [comment]
Yes AE2 only triggered the 1st chunk load, but Mekanism did others.

Besides that there seems to be a more general issue with the network code being rather inefficient at adding something to a grid, esp when adding a larger quantity at once. It looks a bit like it's throwing everything away and starting over.

**Comment by unpairedbracket** [comment]
It shouldn't be, but that does sound like the kind of thing my code would do when it wasn't supposed to be. I've (hopefully) fixed notifyTileChange() to not load chunks, which should improve the situation somewhat. At some point I'll see if I can audit the code a bit to see if there's anything I can do to improve it.
