### ISSUE TITLE
[8.0.0] Client-side code being accessed by server causes crashes

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2229]
This is still crashing: http://pastebin.com/3EzDbvYh

**Comment by halvors** [comment]
Simular to "closed" issue #2226

**Comment by halvors** [comment]
May be relevant: http://www.minecraftforge.net/forum/index.php?topic=23724.0

**Comment by halvors** [comment]
``It's not enough to avoid calling ISound.  If you have a class which has any ISound in it at all, even if you never directly call those methods, and you create that class on the server side, then you will get this error.

The golden rule is - any mod classes which are accessed on the server side should never refer to vanilla client-side-only classes or methods.  It doesn't matter if the code is never called (eg by wrapping it in .isRemote checks), the mere act of loading the server-side class will trigger this error.
Vanilla client-side-only classes should only be referred to by mod client-side-only classes.``

**Comment by unpairedbracket** [comment]
That took a while, but I found it. Turns out you can't ```@SideOnly(Side.CLIENT)``` a field declaration-and-assignment.

**Comment by unpairedbracket** [comment]
This should now be fixed

**Comment by halvors** [comment]
Nive :-)

**Comment by aidancbrady** [comment]
Still occurring for me, actually: http://pastebin.com/fgqmFnZi

**Comment by halvors** [comment]
Sure that was the latest commit by @unpairedbracket you used? Testet it some hours ago, it works fine on server now for me.

**Comment by aidancbrady** [comment]
Yeah, I'm definitely using the very latest commit.  Maybe it's a problem with my environment...

**Comment by halvors** [comment]
I've experiencing that singleplayer running thru eclipse works fine when the server whould crash. And singleplayer is client + server right? So i think that may be the case.

**Comment by aidancbrady** [comment]
Same.  You're positive it works on a dedicated server though, out of eclipse?

**Comment by unpairedbracket** [comment]
@aidancbrady I'm not sure about eclipse - I switched over to IntelliJ IDEA when ForgeGradle came in. They definitely behave in IDEA, and I see no reason why they wouldn't in Eclipse as well.

**Comment by aidancbrady** [comment]
Alright, frustrating.  I need to consider setting up IntelliJ - eclipse is become a bit antiquated.

**Comment by halvors** [comment]
@aidancbrady You've accepted the EULA right? The eula.txt file in the eclipse folder needs to be set to true.

**Comment by kotoroshinoto** [comment]
It was working for me @aidancbrady. You should probably set up a server environment and link in the files from the output directory of gradle builds with ln or mklink (depending on if you're on windows or a unix system). Just to test things. I've never really fully trusted the dev environment "runners"

**Comment by kotoroshinoto** [comment]
I mean, they SHOULD work in principle, but sometimes they miss bugs.

**Comment by aidancbrady** [comment]
Definitely accepted the EULA :)
If anything I'll probably switch to IntelliJ like I said, I've wanted to do that for a while.

**Comment by kotoroshinoto** [comment]
careful with that, it sometimes puts things in the gradle build directories that don't belong there XD

**Comment by halvors** [comment]
@aidancbrady Tested latest commit with Forge 1291 on server, works great.
