### ISSUE TITLE
Energy network broken after update

### ISSUE THREAD

**Issue by Brycey92** [aidancbrady/Mekanism#2392]
I recently updated from Mekanism 7 to 8.0.1.201 on my server, and all the universal energy cables stopped transmitting power. Upon replacement of every cable and cube, things worked normally again. When the chunk is left and becomes unloaded, and then is reentered and becomes loaded, everything is nonfunctional again, and must be broken and replaced to resume the energy flow.

**Comment by aidancbrady** [comment]
I believe I have fixed this in development.  Expect the fix in the next release :)

**Comment by Brycey92** [comment]
Thank you!

**Comment by SalmonSays** [comment]
I'm experiencing this exact same problem still on 8.0.3.206 which released after this issue was opened/closed. Has it been fixed on 8.0.3.207-212?

**Comment by RaRaRasputin** [comment]
I'm still experiencing this problem on .229.
