### ISSUE TITLE
crash with ender io gas conduits with mekansim

### ISSUE THREAD

**Issue by aldra2012** [aidancbrady/Mekanism#2435]
http://pastebin.com/vxrNyPy7

**Comment by aidancbrady** [comment]
EnderIO integration issue :)

**Comment by Cracks777** [comment]
its fixed in the latest release of ender io

**Comment by aldra2012** [comment]
im using the latest release of ender io with the latest mekanism release and still getting it
