### ISSUE TITLE
Server Crash Due to TransporterPathfinder

### ISSUE THREAD

**Issue by MastaC729** [aidancbrady/Mekanism#2508]
Not sure if anyone else has reported this, but I just recently updated to 224, and I get the following crash from my server:

http://pastebin.com/3sa9NCbU

If I downgrade to 216 (before the changelog seems to point at some changes made to these methods), then I have no issues.

**Comment by Imaginativesoul** [comment]
I'm also getting this on the sever side.

**Comment by Shadefang** [comment]
I think I ran into this same Issue. Technic 1.7.10 pack, mekanism 8.1.219 
http://pastebin.com/zBMSagH9

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by Imaginativesoul** [comment]
I just upgraded to .225 and still getting the same error on my upgraded server.  I'll try .226...  I can provide a log if needed.

**Comment by Imaginativesoul** [comment]
Same error for .226

http://pastebin.com/09Grs5X3

**Comment by chaorx** [comment]
Same thing just happened to my local server. 
Running "Mekanism-1.7.10-8.1.1.225.jar"

Judging from the trace, there seems to be a dependency on CodeChickenCore. 
My version is "CodeChickenCore-1.7.10-1.0.4.29-universal.jar"

http://pastebin.com/zERTdviM

**Comment by chaorx** [comment]
Updating solved this
