### ISSUE TITLE
Mekanism machines are rotating in 90° the top textures of nearby blocks

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2617]
I think I discovered something.... big.

Mekanism machines are rotating in 90° the top textures of nearby blocks, sometimes of whole chunk, whose top faces are at the same y-coord.

I was walking around in my base, then I found this:

![2015-05-02_21 01 19](https://cloud.githubusercontent.com/assets/6743303/7443184/69690efc-f10e-11e4-9043-d7d33e345622.png)
Some cobblestone and grass blocks were rotated, you could tell it by the chunk border. I'm using [Aeon resource pack](http://ezerarch.blogspot.com/p/resource-pack.html) (no MCPatcher or Optifine) since its cobblestone texture has straight lines for better visualization.

Now look at the following screenshots taken with the chunk boarder highlighted:
![2015-05-02_20 56 47](https://cloud.githubusercontent.com/assets/6743303/7443164/d59b4550-f10d-11e4-95bd-fe52c6222fea.png)
![2015-05-02_20 57 03](https://cloud.githubusercontent.com/assets/6743303/7443163/d59a9c90-f10d-11e4-9854-8ccb2a640017.png)

Those machines which are full and opaque blocks (e.g. Purification chamber, Crusher, Chemical injection chamber) rotate the top faces of any other blocks like furnaces, cobblestone, grass block, planks etc.

**Comment by aidancbrady** [comment]
Maybe something to do with the new renderer.  Let me check...

**Comment by aidancbrady** [comment]
Should be fixed

**Comment by ate0ate** [comment]
This is definitely still happening in build 8.1.2.229. Kinda problematic, aesthetically speaking, when building a base. Is this only fixed in dev?

**Comment by igoutta** [comment]
Still buggy!!!!!!!!!

**Comment by tterrag1098** [comment]
You really should ref issues in commits...makes it very hard to track this stuff down. This is a pretty serious bug, for the sake of your issue tracker I'd recommend releasing ASAP...

**Comment by tterrag1098** [comment]
I was only able to track it down because I gave you the code to rotate textures in the first place >_>
