### ISSUE TITLE
Oredictionificator and Filters

### ISSUE THREAD

**Issue by NeirRet** [aidancbrady/Mekanism#2676]
I seem to only be able to set up 3 Filters in the Oredictionificator, after that, trying to set a 4th Filter simply replaces the last filter.

I see there is a "scroll" bar on the side of the GUI, but it does not move.

is the Oredictionificator still a WIP, broke, or am I missing something simple to get more than 3 Filters set up?

Thanks

**Comment by aidancbrady** [comment]
Huh, yeah, that's definitely a bug.  I'll try and have it fixed in development by the end of the day.

**Comment by NeirRet** [comment]
Just tossed 8.1.2.230 on my server and client, and working like a champ now, Automated conversion of all oreCopper, oreTin, oreAluminum, oreGold, oreIron, ingotSteel, ingotCopper, ingotTin in my ME system.

Thanks for the quick bug fix !!

**Comment by Dawnflash** [comment]
The issue still persists, only 3 filters allowed, using the latest version. Has the bug returned?

**Comment by NeirRet** [comment]
Confirmed, this problem has returned with current version. Verified this morning.

**Comment by Aralox** [comment]
If you have access to the server and an NBT editor like NBTExplorer, a workaround for this problem is to:
1. Have the Oredictionificator in your inventory in a convenient slot such as 0
2. Go into your player.dat file with an NBT editor 
3. Open up 'Inventory', find the Oredictionificator, open up tag->filters
4. Duplicate a filter a few times so you have more than three, changing the ore type for each new one
5. Save and upload your player.dat file. 

You should now be able to scroll through and add more filters.
