### ISSUE TITLE
Oddness with Elite Logistical Transporter

### ISSUE THREAD

**Issue by cjmace** [aidancbrady/Mekanism#2748]
I have setup a factory and am using a logistical sorter to tag items and send them through a network of logistical transporter pipe to their destinations.  Items are frequently getting hung in the pipe at the point where I have changed the color of the pipe to send them to the proper destination.  I have posted a pic below.

I can make any change to the logistical transporter pipe (add, remove, change a color, etc) and the items will then go to their correct destination, but unless I do that items just appear to get stuck.  They simply sit there and bounce.  

In this pic, I have a joint that has 3 different colors going out, but I have the same issues if there are just two.  Any ideas how to fix this, or did I do something wrong?  This is my first interaction with the newer logistical transporters.  Before I had only seen the old one that only had one type and I never had any issues with it.

The mod loaded is mekansim-1.7.10-7.1.1.127

![screenshot 5](https://cloud.githubusercontent.com/assets/12913490/8185988/79502024-1415-11e5-9c2a-7847f98bbd3a.png)

**Comment by aidancbrady** [comment]
Ah, yeah, this is a bug that was fixed for v8.  Updating should solve the issue :)

**Comment by cjmace** [comment]
Many thanks!

**Comment by cjmace** [comment]
I just upgraded to 8.1.5.237 (latest I can find on the official site) and the issue persists.

:-(

**Comment by aidancbrady** [comment]
This setup works just fine for me: http://puu.sh/irrAw/9cefc3b704.png

Would you post a pic of your entire transporter network?

**Comment by aidancbrady** [comment]
The same works fine with Elite Logistical Transporters.

**Comment by cjmace** [comment]
Mine are Elite Logistical Transporters.  I put a basic one at the joint to slow it down to see if it was a server speed issue, but they still hang with the Basic Logistical Transporter.

I have played around with this in all kinds of configurations and still get the problem.  Originally, the transporters just followed the wall and I tagged just the columns down with the colors, but they hung just going back and forth between two of the colored transporters.  Here is the pic of the entire system.  The sorter on the left feeds this system that only includes the two elite factories (Aqua and Red) and a chest feeding the AE system (Yellow)
![screenshot 15](https://cloud.githubusercontent.com/assets/12913490/8196884/0135709a-145f-11e5-8442-d362c80d84ea.png)
.

What is really odd is the yellow items never get stuck.  Just the Aqua and Red ones.  Both are going to elite factories.  The lower factories in the pics are being fed with AE pipe, just the two imaged are in the transporter network.

**Comment by aidancbrady** [comment]
Correct me if I'm wrong, but it looks like the transporters leading from the two sorters connected to iron chests on the left are all colored yellow.  If this is the case, only yellow colored items should be sent out by the sorter - the other colors wouldn't be able to emit.

**Comment by aidancbrady** [comment]
Looking at this again - if you're emitting from the sorter connected to the left side of the diamond chest on the right of the picture, it looks like there's also a segment of transporter colored yellow in the way.  It's strange that the items are making it past though...

**Comment by cjmace** [comment]
The yellow on the left side of the screenshot is actually a block tagged yellow going through the system.   It goes through fine.  Also many of the Aqua and Red ones go through fine.  Some occasional ones hang up, but never yellow ones.  

All 3 chests/sorters send items to the chest receiving the yellow ones.  I am going to put chests adjacent to the factories to see if that helps.  Will update in a bit.

**Comment by cjmace** [comment]
Ok, the chests did not fix it.  I put the Transporter pipe back in its original design (easier to follow), and now I am getting yellow tagged items getting stuck between the red and aqua channels as seen in this picture.  The pipe circles back to that sorter in the corner that only sends items out tagged  yellow, aqua or red.  

![screenshot 20](https://cloud.githubusercontent.com/assets/12913490/8198305/9022bb1a-1472-11e5-95bb-40ecea1147b8.png)

**Comment by aidancbrady** [comment]
I'll tell you what - I'm going to push this build to master for you to test, it should be available on my website in just a few minutes.  Would you mind reporting back and letting me know if the issue gets fixed?

**Comment by cjmace** [comment]
I am completely baffled.  I can "reset" the network by just adding a random transporter pipe anywhere and/or removing one.  This is not that complex.  It leaves the sorter, goes down 1 channel, passes a yellow exit, a red exit and terminates at an aqua exit.

**Comment by aidancbrady** [comment]
Is this using build 240 that I just pushed?

**Comment by cjmace** [comment]
It is 237.  I will upgrade to 240 in the morning and try again.

**Comment by cjmace** [comment]
Ok, did the upgrade and it appears to have fixed the issue.  Also note that all of the items are going directly to their appropriately colored logistical transport nodes with none of them "dipping" into the ones with mismatched colors!

I will watch it over the next few hours and update you, but all appears to be fine now!

Many many thanks!

**Comment by cjmace** [comment]
Seems to be all good!

**Comment by aidancbrady** [comment]
Awesome!

**Comment by cjmace** [comment]
What part of Atlanta are you in?  I live out between Monroe and Bethlehem on the Athens side.

**Comment by aidancbrady** [comment]
Sandy Springs area, just a bit above 285.  Athens is nice!
