### ISSUE TITLE
Mekanism transports keep breaking

### ISSUE THREAD

**Issue by DesecrationGaming** [aidancbrady/Mekanism#2806]
So I have got back into modded minecraft after a break to play some games I got in the steam summer sale, I started a new world and updated all my mods to there latest versions. A problem I had in the past was that when I placed Mekanism pipes/tubes/etc... it would crash, but this was fixed a while back.

I have been experiencing a problem with the transporters/cables in that they will sometimes break and items will not be extracted/power will not be taken from generators. I can not say for tubes or pipes as I have not got that far in my world (but I did have this problem with my oxygen pipes a while ago).

The only way I can get it to flow again is by breaking and replacing the pipes. My setup is as follows (only temporary):
![2015-07-08_17 55 34](https://cloud.githubusercontent.com/assets/11877565/8576807/83746ef0-259c-11e5-9b86-b8239f31c007.png)

I originally had a gap between the enrichment chamber and energised smelter but I removed it due to this reason, This will be annoying when I get to the 5x ore processing and I will have them everywhere.

I would use Thermal expansion but they don't carry gasses.

I am running 1.7.10 with the latest version of forge (10.13.4.1481) and Mekanism (8.1.5.246)

p.s. (this is just a joke) please somehow tell Yogscast Duncan how to use the digital miner, it is painful to see him fail so much.

**Comment by RAWRwins254** [comment]
Just a question for you: what do you mean they break? You mean they remain connected but don't actually function or that they physically break? If the former, I believe that's been fixed in development, but I can't be certain.

**Comment by othermusketeer** [comment]
This is possibly the same as #2820. I am also experiencing this. Network reader shows part of the line of cables/tube as "No Network". Replacing just the junction of Network/No-Network does not fix it. Instead you have to remove the entire No-Network section and replace it. Essentially rebuilding the network information. Exists with power, transporter, and gas tubes. Not sure about mechanical.

As a temporary solution, and to handle any future problems, it would be nice to have a console command that reinitialize/redefine/rebuild all Mekanism transmitter networks. Probaby an OP only command.

**Comment by RAWRwins254** [comment]
@DesecrationGaming @othermusketeer that sounds right. It's a chunkloading issue. Currently the only way to fight it is ChickenChunks Chunk Loaders. I do not know how @aidancbrady plans to handle this issue, but it's on his to-do list i'm sure.

**Comment by aidancbrady** [comment]
This is #2820 in a nutshell, it also affects transporters due to the new consistent-state networks added in v8.  I'm hoping to fix this soon.

**Comment by othermusketeer** [comment]
@RAWRwins254 No. My whole base is in a chunkloader (chickenChunks even). I'll check if it was happening at chunk boundaries (being chunk loaded it shouldn't matter).

Also, I reverted to Mekanism 245 and it started working again. Could be a coincidence though.
