### ISSUE TITLE
Reactor Logic Adapter setInjectionRate impossible to use

### ISSUE THREAD

**Issue by ArtForz** [aidancbrady/Mekanism#2972]
Trying to call setInjectionRate with anything resembling a integer value just results in "Invalid parameters."
According to my understanding, both CC and OC (via Adapter) always pass lua Number as Double, so the instanceof Integer check in https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorLogicAdapter.java#L197 can never pass.

**Comment by vedalken254** [comment]
Heya @ArtForz! long time no see (Former Bitcointalk user back when that actually existed in a proper state)! Just wanted to say hi since I don't have contact info for ya or anything and also to thank you for reporting that bug... @aidancbrady or @unpairedbracket can actually help you better than I can. Anyways, Nice seeing you again. :)

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by dieselfuelonly** [comment]
Still having this issue when trying to set the injection rate with OpenComputers with Mekanism 8.1.8 included with the 0.2.6 version of the TPPI2 pack.

**Comment by vedalken254** [comment]
@dieselfuelonly first, 8.1.8 doesn't exist officially. TPPI named it wrong. Proof here: 8.1.7.255 for 1.7.10 located at http://aidancbrady.com/mekanism/download/ <--- Official site. As far as I can see, they manually built that version on Xmas. There has been an update which MIGHT have fixed the culprit (data not being sent the correct way) located here: https://github.com/aidancbrady/Mekanism/commit/11574e9454e7ce0630223197573d3f3ed5a63ef7 which was committed to the development branch on 12/31/2015.

The master branch (from which all official releases are made as far as source code) hasn't had a commit since November 25th, 2015. Basically, TPPI2 pack authors are using a "dev build" they manually compiled. I heavily recommend you contact them and have them issue an update for a rebuild of the mekanism mod. I'm kinda surprised they don't have their own support thing for these types of things given they're using a manually compiled build that isn't officially released.

Veddy
