### ISSUE TITLE
Server Crash on Existing World when Updated

### ISSUE THREAD

**Issue by cutter4ever** [aidancbrady/Mekanism#3059]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/9/16 4:12 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at mekanism.common.tile.TileEntityNoisyElectricBlock.<init>(TileEntityNoisyElectricBlock.java:34)
	at mekanism.common.tile.TileEntityChargepad.<init>(TileEntityChargepad.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:104)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at mods.immibis.chunkloader.porting.ChunkLoadInterface132.addChunk(ChunkLoadInterface132.java:106)
	at mods.immibis.chunkloader.data.WorldLoaderList.tick(WorldLoaderList.java:319)
	at mods.immibis.chunkloader.DimensionalAnchors.onTickInGame(DimensionalAnchors.java:548)
	at mods.immibis.core.api.porting.PortableBaseMod$TickEventServerHandler.tickEventServer(PortableBaseMod.java:13)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_537_TickEventServerHandler_tickEventServer_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 359736752 bytes (343 MB) / 1105199104 bytes (1054 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 4 total; -XX:+UseG1GC -XX:+UseStringDeduplication -Xmx4G -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 145 mods loaded, 145 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-2} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-2} [Applied Energistics 2] (appliedenergistics2-rv3-beta-2.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.1.9} [AE2 Stuff] (ae2stuff-rv3-0.5.1.9-mc1.7.10.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJAAAA	AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
	UCHIJAAAA	bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1614-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	Forestry{4.2.4.52} [Forestry for Minecraft] (forestry_1.7.10-4.2.4.52.jar) 
	UCHIJAAAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-248} [Botania] (Botania r1.8-248.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	catwalks{2.0.3} [Catwalks Mod] (catwalks-2.0.3.jar) 
	UCHIJAAAA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.3.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-3.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.32} [MrTJPCore] (MrTJPCore-1.1.0.32-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre10.93} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V10d.jar) 
	UCHIJAAAA	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V10d.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V10d.jar) 
	UCHIJAAAA	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V10b.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.422_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.422_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAAAA	ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V10b.jar) 
	UCHIJAAAA	extracells{2.3.7} [Extra Cells 2] (ExtraCells-1.7.10-2.3.7b176.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	gendustry{1.6.3.132} [GenDustry] (gendustry-1.6.3.132-mc1.7.10.jar) 
	UCHIJAAAA	pressure{1.2.5.125} [Pressure Pipes] (pressure-1.2.5.125-mc1.7.10.jar) 
	UCHIJAAAA	advgenerators{0.9.19.120} [Advanced Generators] (generators-0.9.19.120-mc1.7.10.jar) 
	UCHIJAAAA	GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V10b.jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	Mekanism{8.1.8} [Mekanism] (Mekanism-1.7.10-8.1.8.256.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.8} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.8.256.jar) 
	UCHIJAAAA	MekanismTools{8.1.8} [MekanismTools] (MekanismTools-1.7.10-8.1.8.256.jar) 
	UCHIJAAAA	millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) 
	UCHIJAAAA	mfrmagiccropscompat{1.0} [MinefactoryReloaded & MagicalCrops extra compatibility] (minefactory-magicalcrops-compatibility-1.0.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre10.93} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre10.93-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.10} [Morpheus] (Morpheus-1.7.10-1.6.10.jar) 
	UCHIJAAAA	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
	UCHIJAAAA	NuclearCraft{0.0.1.5} [NuclearCraft] (NuclearCraft-0.0.1.5--1.7.10.jar) 
	UCHIJAAAA	clayspawn{1.7.10a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.10a.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre10.93} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre10.93} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre10.93-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre10.93} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
	UCHIJAAAA	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V10d.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.6.1} [Storage Drawers] (StorageDrawers-1.7.10-1.6.1.jar) 
	UCHIJAAAA	StorageDrawersForestry{1.7.10-1.0.3} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.3.jar) 
	UCHIJAAAA	StorageDrawersMisc{1.7.10-1.0.0} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.0.0.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.0.3} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.0.3.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.3} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.3.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: beta rv3-beta-2 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.4.6-hotfix.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv3-beta-2.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.7.10-0.0.0.6.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1614-universal.jar
		* BotaniaAPI (75) from Botania r1.8-248.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.14.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
		* CoFHAPI (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
		* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from buildcraft-7.1.14.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.10) from NuclearCraft-0.0.1.5--1.7.10.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.4.52.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.4.52.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.375.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.3.132-mc1.7.10.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.8.256.jar
		* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V10d.jar
		* pressureAPI (1.2.5.125) from pressure-1.2.5.125-mc1.7.10.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.1.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* TravellersGear|API (1.0) from TravellersGear-1.7.10-1.16.6.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.13 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from buildcraft-7.1.14.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by XFactHD** [comment]
The crash report says that a vanilla Minecraft class is missing. Can you please make a new Minecraft instance, install all the mods and try to reproduce this?

**Comment by halomantis** [comment]
Ran into the same problem on update, different mod list but same error.  Made a new instance and installed all the mods fresh and the issue was still present.  Interesting note:  Single Player on the map works just fine.

**Comment by aidancbrady** [comment]
Ooh, thanks for catching this! Just pushed build 257, it should fix this issue.

**Comment by adigyran** [comment]
this is not fixed even in 257. this exception throws any ticks

**Comment by aidancbrady** [comment]
Do you have a log?

**Comment by adigyran** [comment]
i created separated issue https://github.com/aidancbrady/Mekanism/issues/3060

**Comment by aidancbrady** [comment]
Fixed, #258 :)
