### ISSUE TITLE
Mekanism not working with flux ducts

### ISSUE THREAD

**Issue by Just-some-cannibal** [aidancbrady/Mekanism#3291]
In mekanism v8, I used flux ducts to transport energy from my reactor to my base (due to cables only transporting 320 kj/t.) When I updated to v9, all of my energy stopped in my base. This appears to be only bugged with cables connecting to flux ducts. I have also found that flux ducts give energy to universal cables, but universal cables won't give energy to flux ducts.

**Comment by HadesDurin** [comment]
i announced that already and there is a fix for it in the 271 version on the page just below the large 270 download

**Comment by SteelShot** [comment]
Yeah, same here, output < 2.147B and the ducts fail. For now just reduce the output to be below 2.147 billion RF/t

**Comment by HadesDurin** [comment]
where you get that much output from?
DE? if so the DE RF Storage Block Tier 7 is bugged and don't let u put more than 2.147B RF into it.

btw if you switch all mekanism to Cofh mod cables all is fine, which is until the update from 1.7.10 to 1.8 or 1.9 a problem at the moment.

**Comment by SteelShot** [comment]
The output = from my 18x18x18 Induction matrix. DE is built on the RF API so yes, it wont accept more that 2.147B as that -2147483647 to 2147483647 is the max integer values, its not a bug it just does not know what to do with a larger number. If it was built using Longs the limit then would be 9223372036854775807

**Comment by darknesschaos** [comment]
I am having a similar issue with Mekanism and tesseracts right now. I wonder if this is related.

**Comment by SteelShot** [comment]
Its still the same issue,  dont push more thnay 2.147Billion rf to any machine that uses RF,  its the max amount, if you push more all that power turns into 0.

**Comment by HadesDurin** [comment]
you describe it above why 2,147B RF/t is the most, btw an Induction Matrix should store more than the 2,147B RF. one Ultimate Induction Cell can store more than 200B RF

**Comment by SteelShot** [comment]
when it comes to RF based machines yes, but Aidan uses Mekanism Joules(which is most likely writen using longs) and gives conversion support to RF. Yes at the time when RF was introduced in 1.6.4, no one expected to produce more than the Max integer value. Tho now we got mekanism and Reika's ReactorCraft that can reach extreme RF production.

**Comment by HadesDurin** [comment]
you are right, but at the moment max handleable by mekanism cable is 128kRF/t and the only better way is for me cofh mod cables. wondering, that mekanism provides multistorage blocks with hugh input output values, but only mid tier energy transfer cpompared to cofh mod top tier cable.

so as of 1.8/1.9 i wait for mods that provide cables to transfer the long value energies around.
one of my goals is to get a draconic reactor up and running which produce around 560k RF/t and there is no alternative for me as to use cofh mod cable then.

**Comment by SteelShot** [comment]
there is the RF cable from ElectriCraft but that also does 2.147Billion max :/ The way I see it to get a better cable in 1.7.10 is by requesting some1 to code it

**Comment by aidancbrady** [comment]
Yeah yeah fine, I'll use tesla :)

**Comment by SteelShot** [comment]
No one is forcing you to use Tesla, its just seems abit better than RF, the limit wise and also it works with the latest version of MC :)

**Comment by aidancbrady** [comment]
Trust me, I had plans to support Tesla anyway. I hope the rest of the modding community does the same...

**Comment by SteelShot** [comment]
That would be nice, but i dont see alot of peeps moving to it YET, i'd say when there a high procentage of authors moving to it, the rest should follow, same happened with RF

**Comment by HadesDurin** [comment]
i dig into ElectiCraft and realise, that it needs rotarycraft to run.
maybe as a workaround mekanism cable transferrates can be raised?

**Comment by SteelShot** [comment]
yeah it does need that, I only see

I:UltimateCableCapacity=320000 dont know if that incrases the flow rate tho, give it a try

**Comment by HadesDurin** [comment]
that is the value i guess, will try it out after restarting minecraft

**Comment by SteelShot** [comment]
Yeah, changing the value, increases the flow rate

**Comment by HadesDurin** [comment]
yeah tested it for myself now, new problem is, the value is for J and i turn it for myself in RF.
So when i decide to go with the max value is that the max integer of 2,147B J?
also it didn't fix the issue af the original poster including for me the mekanism ->TE crossworking in 1.7.10

**Comment by SteelShot** [comment]
The issue here i'd say is the know issue from before, that was reported a week or so ago #3252

**Comment by aidancbrady** [comment]
Should be fixed in the latest Mekanism build.

**Comment by SteelShot** [comment]
is this for the 9.0.2.274 Build?
it still doesnt seem to work with Cryo Ducts
![2016-06-16_03 03 45](https://cloud.githubusercontent.com/assets/5291010/16103300/329cfdf8-336f-11e6-8373-b3b97b425d55.png)

it does tho work with the lover tier conduits
![2016-06-16_03 05 25](https://cloud.githubusercontent.com/assets/5291010/16103304/402049f8-336f-11e6-9a41-d47bd86d8902.png)
