### ISSUE TITLE
1.10.2 TESLA Compatibility Crash

### ISSUE THREAD

**Issue by JoltEffect** [aidancbrady/Mekanism#3636]
Using
Tesla-1.10.2-1.2.1.46.jar
Mekanism-1.10.2-9.1.1.290.jar
JustSolars 1.10.2.R1-1.0.jar (My own Tesla Mod) which includess the 3 test blocks from Tesla (Analyiser/BlackHole and CreativeCube), when connecting my Solar's to the BlackHole and Analyiser no problems at all.  Connecting you energycubes to the blackhold no problems.  But connect my Solars or the Tesla Creative EnergyCybe, the following crash report is applicable.

`[23:08:41] [Client thread/INFO]: [CHAT] <PROFILE NAME> has just earned the achievement [Taking Inventory]
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor0(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityBasicMachine.getCapability(TileEntityBasicMachine.java:329)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.darkhax.tesla.lib.TeslaUtils.getConnectedCapabilities(TeslaUtils.java:276)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.darkhax.tesla.lib.TeslaUtils.distributePowerToAllFaces(TeslaUtils.java:295)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at com.jolteffect.justsolars.tileentity.TileEntityCreativePower.func_73660_a(TileEntityCreativePower.java:39)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_72939_s(World.java:1802)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[23:09:03] [Client thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor0(Unknown Source)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor(Unknown Source)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityBasicMachine.getCapability(TileEntityBasicMachine.java:329)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.darkhax.tesla.lib.TeslaUtils.getConnectedCapabilities(TeslaUtils.java:276)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.darkhax.tesla.lib.TeslaUtils.distributePowerToAllFaces(TeslaUtils.java:295)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at com.jolteffect.justsolars.tileentity.TileEntityCreativePower.func_73660_a(TileEntityCreativePower.java:39)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_72939_s(World.java:1802)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[23:09:04] [Server thread/INFO]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Thread.run(Unknown Source)
[23:09:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at net.darkhax.tesla.lib.TeslaUtils.distributePowerToAllFaces(TeslaUtils.java:296) ~[TeslaUtils.class:?]
	at com.jolteffect.justsolars.tileentity.TileEntityCreativePower.func_73660_a(TileEntityCreativePower.java:39) ~[TileEntityCreativePower.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[23:09:04] [Server thread/ERROR]: This crash report has been saved to: D:\Minecraft\MultiMC\instances\1.10.2\minecraft\crash-reports\crash-2016-08-12_23.09.04-server.txt`

**Comment by SergeySave** [comment]
I am getting this issue myself. It seems to be occurring because mekanism.common.capabilities.CapabilityWrapperManager is trying to find a constructor in mekanism.common.integration.TeslaIntegration that has the arguments: mekanism.common.base.IEnergyWrapper and net.minecraft.util.EnumFacing but the constructor in that file uses the arguments mekanism.common.tile.TileEntityElectricBlock and net.minecraft.util.EnumFacing.

**Comment by SergeySave** [comment]
I also get a AbstractMethodError when trying to give power to a universal cable however this cable does not want to connect to my block that has the ITeslaProducer capability. This non-connection issue is much harder for me to debug as I don't see a stacktrace.

**Comment by rreeggkk** [comment]
I am getting this issue myself. It seems to be occurring because mekanism.common.capabilities.CapabilityWrapperManager is trying to find a constructor in mekanism.common.integration.TeslaIntegration that has the arguments: mekanism.common.base.IEnergyWrapper and net.minecraft.util.EnumFacing but the constructor in that file uses the arguments mekanism.common.tile.TileEntityElectricBlock and net.minecraft.util.EnumFacing.

I also get a AbstractMethodError when trying to give power to a universal cable however this cable does not want to connect to my block that has the ITeslaProducer capability. This non-connection issue is much harder for me to debug as I don't see a stacktrace.

**Comment by canitzp** [comment]
With commit a4a335a8b938b51c242937c42fbc1fe1114f6a0a nearly every broken tesla integration is fixed but he forot to rename https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L347 to 'tesla'. This is the reason for the AbstractMethod crash, also related to Ellpeck/ActuallyAdditions#194

**Comment by aidancbrady** [comment]
Fixed in dev, I'll be pushing this change very soon.

**Comment by TehBigA** [comment]
This is still happening. When will the fix be pushed?
`[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net
.minecraft.util.EnumFacing)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at java.lang.Class.getConstructor0(Unknown Source)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at java.lang.Class.getConstructor(Unknown Source)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at mekanism.common.tile.TileEntityQuantumEntangloporter.getCapability(TileEntityQuantumEntangloporter.java:687)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.power.tesla.TeslaAdapter.getCapability(TeslaAdapter.java:55)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.power.tesla.TeslaAdapter.getPowerInterface(TeslaAdapter.java:41)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:42)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:458)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:404)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.conduit.AbstractConduit.updateConnections(AbstractConduit.java:429)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:404)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:235)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.world.World.func_72939_s(World.java:1804)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[07:32:06] [Server thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]:        at java.lang.Thread.run(Unknown Source)
`
