### ISSUE TITLE
Unable to place offhand items while holding Atomic Disassembler

### ISSUE THREAD

**Issue by Californ1a** [aidancbrady/Mekanism#3876]
This is mainly an issue with torches. You have to switch your mainhand item away from the AD in order to place whatever item is in your offhand. This is likely because the AD has right-click functions such as tilling soil, but it shouldn't try to perform any of those actions on blocks it can't (like stone), which would then allow you to use your offhand item without switching away from the AD in mainhand. Potentially it should only try to do right-click actions when you click on the correct side of the block (such as the top of dirt to till it), allowing you to still place offhand torches on the side of dirt without switching to a different mainhand item. 

Minecraft: 1.10.2
Forge: 12.18.1.2094
Mekanism: 9.2.0

**Comment by momerathe** [comment]
I'd like to second this. Now I'm used to caving with a stack of torches in my off hand, going back to the old way is a struggle.

**Comment by thommy101** [comment]
Can confirm this in latest version.

Code analysis:
ItemAtomicDisassembler always returns an ActionResult of SUCCESS even if there isn't anything to do.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by thommy101** [comment]
Uhm... Think this isn't fixed. Now it always places items of the offhand and tilling soil doesn't work anymore.

**Comment by aidancbrady** [comment]
Actually fixed :)
