### ISSUE TITLE
[1.10.2, 9.2.0.294] WAILA names and icons are incorrect.

### ISSUE THREAD

**Issue by PJB3005** [aidancbrady/Mekanism#3983]
Seems to affect the same things that the JEI bug are affected by.

Exhibit A, a crusher:

![](http://i.imgur.com/b8pSQu0.png)

Exhibit B, a basic bin:

![](http://i.imgur.com/ytVj9gz.png)

**Comment by thommy101** [comment]
This is already fixed in the latest version of github (9.2.1), but there is no download for it yet. You can download the most recent test build (with some fixes of me) at my pull request 3967
Also make sure you're using the latest version of waila.

**Comment by PJB3005** [comment]
Ah, okay. I tried to search for an issue and couldn't find one so, sorry.

**Comment by PJB3005** [comment]
I just built the `9.2.1` from GitHub (branch 1.10), this issue still exists.

**Comment by PJB3005** [comment]
Okay I actually built from https://github.com/aidancbrady/Mekanism/pull/3967 but I highly doubt that that PR can somehow regress the fix in 10 LOC added, and the branch is up to date with the main repo's `1.10` branch.

**Comment by thommy101** [comment]
I'm sorry.. Mixed up JEI and Waila. I've been using The One Probe since some time, which does display it correctly.

**Comment by JaSpr** [comment]
I worked on this for a while and found that the fault isn't in Mekanism at all.  It turns out that the WAILA code for getting the targeted block was incorrect.

I have submitted a pull request to WAILA with the resolution.

https://bitbucket.org/ProfMobius/waila/pull-requests/47

Nothing to fix on this end.
