### ISSUE TITLE
Configurator Wrench Mode not dropping items

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4047]
In Minecraft 1.10.2 when holding something in the Off-Hand the shift-right clicking an item the item is not dropped to be picked. With the Off-Hand empty it works fine.

Mekanism-1.10.2-9.2.1.295

**Comment by aidancbrady** [comment]
Should be fixed in latest release

**Comment by LewdNeko** [comment]
Hate to be that guy who comments on a post from 4 years ago but this is still an issue

**Comment by duncanwebb** [comment]
Honestly, I don't know. The ticket was closed, so I guess that it was fixed. The right-click stuff in Minecraft has changed a lot since 1.14 or maybe 1.12,

**Comment by SpaceTy** [comment]
And 2 years later this is still an issue....
