### ISSUE TITLE
Mechanical pipe compatibility with Extreme Reactors

### ISSUE THREAD

**Issue by black-and-blue** [aidancbrady/Mekanism#4215]
When running Infinity Lite 1.10, I'm pumping water/steam to my turbine using Mekanism's Ultimate Mechanical pipes, which works pretty well, except that they disconnect from the reactor and turbine every time the server reboots.

Not sure whether it's an issue with Mekanism or Extreme Reactors, but it's a bit annoying since it means I can't completely automate power generation; with daily server restarts, I have to make sure I log on at least once a day to reconnect the pipes.

**Comment by Cop4Terminator** [comment]
I have the same problem. it is soo annoying.

**Comment by StefanTT** [comment]
This happens also with EnderIO fluid conduits.

**Comment by thommy101** [comment]
Should be fixed in ExtremeReactors 0.4.5.28.

**Comment by StefanTT** [comment]
Fingers crossed ...

My problem is that the Extreme Reactors reactor is disconnected from the adjacent turbine upon server start. This is not fixed in 0.4.5.28. Let's hope that it works now when using pipes in between.

However, I am even more confident that this is not a Mekanism problem and this issue could be closed.
