### ISSUE TITLE
[1.11.2] No null facing handling of inventories

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4336]
Getting the inventory of a null side is a valid operation. The purpose of getting the inventory from the null facing is something like "get the internal inventory". This is used by mods who don't care about facings like The One Probe and RFTools.

~~~This also applies to fluid holders, althrough I didn't test if it is also affected by the same "bug".~~~
Fluid holders aren't affected.

Log:
https://gist.github.com/thommy101/0bd888d4768ceaf564d72789715ccaf5

**Comment by aidancbrady** [comment]
Fixed!

**Comment by thommy101** [comment]
Cannot confirm correct fix. It's still throwing a NPE with the same stacktrace.
Also the purpose of the null facing is showing all inventory, not nothing. Looking at the code of a vanilla furnace, it returns all three slots on the null facing and allowing other mods (like The One Probe) show all the three slots in the heads up display.
