### ISSUE TITLE
[1.11] Glow Pannel Sync Issue

### ISSUE THREAD

**Issue by RODragon** [aidancbrady/Mekanism#4379]
The glow panels seem to be suffering from a sync issue from server to client. When a client loads the panels, they are loaded locally as the black variant, in the position as if they were placed on the ground. When picked up, they are the variant that was originally placed down. Additionally when they are in this default state, the server rubberbands the client's position out of the occupied location of where the panel should be. Suggesting the server is keeping the proper data, but not syncing it to the client. If the client is around when the block is placed, the data is synced correctly and the block is normal until it needs to be loaded locally again. 

Happens in both multiplayer and single player, and when Mekanism is the only mod loaded.
Forge 13.20.0.2298
Latest 1.11 branch commit.

**Comment by thommy101** [comment]
I've also noticed a desync in a single player world. With energy cubes reverting to basic (and empty) variants which where full creative. 

Haven't tried to break them and see what they drop.

**Comment by aidancbrady** [comment]
Should be fixed, thanks for letting me know

**Comment by RODragon** [comment]
I just tested in both single and multiplayer and this is still an issue.

**Comment by aidancbrady** [comment]
Ah, found the issue. Let me know if the latest build works for you.

**Comment by RODragon** [comment]
Seems to work as intended. Thanks! :D
