### ISSUE TITLE
[1.10.2] NullPointerException while looking at PRC with Waila(Hwyla)

### ISSUE THREAD

**Issue by DeadSix27** [aidancbrady/Mekanism#4499]
#### Issue description:
When you look at the PRC with Waila(Hwyla) it will produce the linked errors.

#### Versions:
**Forge:** 1.10.2-12.18.3.2297
**Mekanism:** 9.2.2.301

stacktrace: https://gist.github.com/DeadSix27/fb9861c33657f41f0eb7a238c6bfcbd7

Not sure if this issue is on mekanism's side or wailas, since mekanism is the top entry in the stack I reported it here.

**Comment by thommy101** [comment]
I recommend the usage of hwyla, as it's the successor of waila and currently maintained. 
Waila is outdated and may not work correctly. 

(an other alternative is the one probe)

**Comment by DeadSix27** [comment]
@thommy101 I am using Hwyla.

**Comment by thommy101** [comment]
Okey, didn't read that the first time (maybe you edited it). It's certainly on Mekanism's side, my guess is that this is one of the issues that has been solved in the 1.11.2 release.. The main focus has shifted towards 1.11.2.

I however still have the intention of backporting a lot of 1.11.2 fixes to the 1.10.2 version to make one final more stable release.

**Comment by DeadSix27** [comment]
@thommy101 It's alright, I often edit posts as I revisit them and find mistakes, let me change the title to make it even clearer in the future.

And Nice, looking forward to the 1.10 back-ports!

**Comment by thommy101** [comment]
@DeadSix27 Is there a way to chat with/contact you for an experimental (not fully tested) 1.10.2 version?

**Comment by DeadSix27** [comment]
@thommy101 Sure! I compiled the version I currently use as well :p Since it has a few fixes not in the public release too I think

**Comment by thommy101** [comment]
Do you have Discord by any chance? I'm thommy101 # 2072 over there.

**Comment by DeadSix27** [comment]
@thommy101 I've added you.

**Comment by thiakil** [comment]
Hmm this should have been fixed in 0aa1c84668d2a5b23b08766a847c264ddbf453fd, though I'm not sure if that made the curseforge release

**Comment by thommy101** [comment]
I've tested this with @DeadSix27, the current release doesn't fix it, the accepted backport fixes the issue :)
